version: '3.2'
services:
  sharedpg:
    container_name: sharedpg
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
    - shared
networks:
  shared:
    name: shared
    driver: bridge
